const User = require('./../models/User');
const Room = require('./../models/Room');

var ioEvents = function(io) {
    // const adminNamespace = io.of('/admin');
    io.on('connection', function(socket){
        socket.on('account_info', function(data) {
            User.findOne({userName: data.userName}).exec(function (err, user) {
                if (err) {
                    console.log('err', err)
                    return done(err);
                }
                
                if (user) {
                    /**
                     * Change socket id was generated by server to user Id
                     */
                    console.log('loginttt');
                    let uRoom = 'room_' + user.id;
                    socket.join(uRoom);
                    io.to(uRoom).emit('test_mess', 'tttttttttttttt');
                } else {
                    /**
                     * create new user
                     */
                    var user = new User();
                    user.userName = data.userName;
                    user.phoneNumber = '01626878789';
                    user.email = data.email;
                    user.password = data.password;

                    user.save(function(err) {
                        if (err) {
                            console.log('err', err);
                        } 
                        console.log('create new user successfully')
                    })
                }
            });
        });

        /**
         * Event client disconnect
         */
        socket.on('disconnect', () => {
            console.log('reason');
        });
    });
}

module.exports = ioEvents;